---
title: "Final Project"
author: "Yamini and Matin"
date: "11/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Code for Predicting NYC AirBnB Prices:
```{r}
#importing datasets
train = read.csv("AirBnB/train.csv", header = T)
test = read.csv("AirBnB/test.csv",header = T)
```

```{r}
#beginning EDA
head(train)
plot(train$price)
for (i in 1:ncol(train)) {
print(colnames(train)[i])
print(sum(complete.cases(train[,i])))
}
train$neighbourhood = as.factor(train$neighbourhood)
barplot(table(train$neighbourhood), table(train$price))
library(VIM)
matrixplot(train)
VIM::aggr(train)
train = train[,c(1,5:12,14:16)]
```

```{r}
#imputing missing data
library(mice)
fcs = mice(train[,c(1:8)], m=5, method="pmm")
train_comp = complete(fcs,2)
train$reviews_per_month = train_comp$reviews_per_month
VIM::aggr(train)
train = train[,c(1,2,4:11)]
```

```{r}
#creating model
set.seed(1111)
ind = sample(34226,23957)
train_cv = train[ind,]
test_cv = train[-ind,]
```

```{r}
library(rpart)
library(randomForest)

#rf
model = randomForest(price~., data=train_cv)

varImpPlot(model)
plot(model)
preds = predict(model, newdata=test_cv, type = "class")

preds_final = predict(model, newdata=test, type = "class")
test$price = preds_final
sub = test[,c(1,16)]
write.csv(sub, file = "C:\\Users\\admin\\Desktop\\Course Work\\STAT 388\\Final Project\\AirBnB\\finalpredictions.csv", row.names = FALSE)
```
